package com.hust.htd.persistence.model;

import java.util.Date;

public class Anonymous {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anonymous.anonymous_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long anonymousId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anonymous.anonymous_ip_address
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String anonymousIpAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anonymous.anonymous_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String anonymousName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anonymous.anonymous_created_datetime
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Date anonymousCreatedDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anonymous.anonymous_id
     *
     * @return the value of anonymous.anonymous_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getAnonymousId() {
        return anonymousId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anonymous.anonymous_id
     *
     * @param anonymousId the value for anonymous.anonymous_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setAnonymousId(Long anonymousId) {
        this.anonymousId = anonymousId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anonymous.anonymous_ip_address
     *
     * @return the value of anonymous.anonymous_ip_address
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getAnonymousIpAddress() {
        return anonymousIpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anonymous.anonymous_ip_address
     *
     * @param anonymousIpAddress the value for anonymous.anonymous_ip_address
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setAnonymousIpAddress(String anonymousIpAddress) {
        this.anonymousIpAddress = anonymousIpAddress == null ? null : anonymousIpAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anonymous.anonymous_name
     *
     * @return the value of anonymous.anonymous_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getAnonymousName() {
        return anonymousName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anonymous.anonymous_name
     *
     * @param anonymousName the value for anonymous.anonymous_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setAnonymousName(String anonymousName) {
        this.anonymousName = anonymousName == null ? null : anonymousName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anonymous.anonymous_created_datetime
     *
     * @return the value of anonymous.anonymous_created_datetime
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Date getAnonymousCreatedDatetime() {
        return anonymousCreatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anonymous.anonymous_created_datetime
     *
     * @param anonymousCreatedDatetime the value for anonymous.anonymous_created_datetime
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setAnonymousCreatedDatetime(Date anonymousCreatedDatetime) {
        this.anonymousCreatedDatetime = anonymousCreatedDatetime;
    }
}