package com.hust.htd.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnonymousExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public AnonymousExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAnonymousIdIsNull() {
            addCriterion("anonymous_id is null");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdIsNotNull() {
            addCriterion("anonymous_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdEqualTo(Long value) {
            addCriterion("anonymous_id =", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdNotEqualTo(Long value) {
            addCriterion("anonymous_id <>", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdGreaterThan(Long value) {
            addCriterion("anonymous_id >", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdGreaterThanOrEqualTo(Long value) {
            addCriterion("anonymous_id >=", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdLessThan(Long value) {
            addCriterion("anonymous_id <", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdLessThanOrEqualTo(Long value) {
            addCriterion("anonymous_id <=", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdIn(List<Long> values) {
            addCriterion("anonymous_id in", values, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdNotIn(List<Long> values) {
            addCriterion("anonymous_id not in", values, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdBetween(Long value1, Long value2) {
            addCriterion("anonymous_id between", value1, value2, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdNotBetween(Long value1, Long value2) {
            addCriterion("anonymous_id not between", value1, value2, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressIsNull() {
            addCriterion("anonymous_ip_address is null");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressIsNotNull() {
            addCriterion("anonymous_ip_address is not null");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressEqualTo(String value) {
            addCriterion("anonymous_ip_address =", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressNotEqualTo(String value) {
            addCriterion("anonymous_ip_address <>", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressGreaterThan(String value) {
            addCriterion("anonymous_ip_address >", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("anonymous_ip_address >=", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressLessThan(String value) {
            addCriterion("anonymous_ip_address <", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressLessThanOrEqualTo(String value) {
            addCriterion("anonymous_ip_address <=", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressLike(String value) {
            addCriterion("anonymous_ip_address like", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressNotLike(String value) {
            addCriterion("anonymous_ip_address not like", value, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressIn(List<String> values) {
            addCriterion("anonymous_ip_address in", values, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressNotIn(List<String> values) {
            addCriterion("anonymous_ip_address not in", values, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressBetween(String value1, String value2) {
            addCriterion("anonymous_ip_address between", value1, value2, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousIpAddressNotBetween(String value1, String value2) {
            addCriterion("anonymous_ip_address not between", value1, value2, "anonymousIpAddress");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameIsNull() {
            addCriterion("anonymous_name is null");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameIsNotNull() {
            addCriterion("anonymous_name is not null");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameEqualTo(String value) {
            addCriterion("anonymous_name =", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotEqualTo(String value) {
            addCriterion("anonymous_name <>", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameGreaterThan(String value) {
            addCriterion("anonymous_name >", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameGreaterThanOrEqualTo(String value) {
            addCriterion("anonymous_name >=", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameLessThan(String value) {
            addCriterion("anonymous_name <", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameLessThanOrEqualTo(String value) {
            addCriterion("anonymous_name <=", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameLike(String value) {
            addCriterion("anonymous_name like", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotLike(String value) {
            addCriterion("anonymous_name not like", value, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameIn(List<String> values) {
            addCriterion("anonymous_name in", values, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotIn(List<String> values) {
            addCriterion("anonymous_name not in", values, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameBetween(String value1, String value2) {
            addCriterion("anonymous_name between", value1, value2, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousNameNotBetween(String value1, String value2) {
            addCriterion("anonymous_name not between", value1, value2, "anonymousName");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeIsNull() {
            addCriterion("anonymous_created_datetime is null");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeIsNotNull() {
            addCriterion("anonymous_created_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeEqualTo(Date value) {
            addCriterion("anonymous_created_datetime =", value, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeNotEqualTo(Date value) {
            addCriterion("anonymous_created_datetime <>", value, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeGreaterThan(Date value) {
            addCriterion("anonymous_created_datetime >", value, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("anonymous_created_datetime >=", value, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeLessThan(Date value) {
            addCriterion("anonymous_created_datetime <", value, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("anonymous_created_datetime <=", value, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeIn(List<Date> values) {
            addCriterion("anonymous_created_datetime in", values, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeNotIn(List<Date> values) {
            addCriterion("anonymous_created_datetime not in", values, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeBetween(Date value1, Date value2) {
            addCriterion("anonymous_created_datetime between", value1, value2, "anonymousCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousCreatedDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("anonymous_created_datetime not between", value1, value2, "anonymousCreatedDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table anonymous
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}