package com.hust.htd.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class ImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public ImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImageIdIsNull() {
            addCriterion("image_id is null");
            return (Criteria) this;
        }

        public Criteria andImageIdIsNotNull() {
            addCriterion("image_id is not null");
            return (Criteria) this;
        }

        public Criteria andImageIdEqualTo(Long value) {
            addCriterion("image_id =", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdNotEqualTo(Long value) {
            addCriterion("image_id <>", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdGreaterThan(Long value) {
            addCriterion("image_id >", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("image_id >=", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdLessThan(Long value) {
            addCriterion("image_id <", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdLessThanOrEqualTo(Long value) {
            addCriterion("image_id <=", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdIn(List<Long> values) {
            addCriterion("image_id in", values, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdNotIn(List<Long> values) {
            addCriterion("image_id not in", values, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdBetween(Long value1, Long value2) {
            addCriterion("image_id between", value1, value2, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdNotBetween(Long value1, Long value2) {
            addCriterion("image_id not between", value1, value2, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNull() {
            addCriterion("image_url is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNotNull() {
            addCriterion("image_url is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlEqualTo(String value) {
            addCriterion("image_url =", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotEqualTo(String value) {
            addCriterion("image_url <>", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThan(String value) {
            addCriterion("image_url >", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("image_url >=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThan(String value) {
            addCriterion("image_url <", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThanOrEqualTo(String value) {
            addCriterion("image_url <=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLike(String value) {
            addCriterion("image_url like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotLike(String value) {
            addCriterion("image_url not like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIn(List<String> values) {
            addCriterion("image_url in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotIn(List<String> values) {
            addCriterion("image_url not in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlBetween(String value1, String value2) {
            addCriterion("image_url between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotBetween(String value1, String value2) {
            addCriterion("image_url not between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbIsNull() {
            addCriterion("image_url_thumb is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbIsNotNull() {
            addCriterion("image_url_thumb is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbEqualTo(String value) {
            addCriterion("image_url_thumb =", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbNotEqualTo(String value) {
            addCriterion("image_url_thumb <>", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbGreaterThan(String value) {
            addCriterion("image_url_thumb >", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbGreaterThanOrEqualTo(String value) {
            addCriterion("image_url_thumb >=", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbLessThan(String value) {
            addCriterion("image_url_thumb <", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbLessThanOrEqualTo(String value) {
            addCriterion("image_url_thumb <=", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbLike(String value) {
            addCriterion("image_url_thumb like", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbNotLike(String value) {
            addCriterion("image_url_thumb not like", value, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbIn(List<String> values) {
            addCriterion("image_url_thumb in", values, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbNotIn(List<String> values) {
            addCriterion("image_url_thumb not in", values, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbBetween(String value1, String value2) {
            addCriterion("image_url_thumb between", value1, value2, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageUrlThumbNotBetween(String value1, String value2) {
            addCriterion("image_url_thumb not between", value1, value2, "imageUrlThumb");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordIsNull() {
            addCriterion("image_seo_keyword is null");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordIsNotNull() {
            addCriterion("image_seo_keyword is not null");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordEqualTo(String value) {
            addCriterion("image_seo_keyword =", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordNotEqualTo(String value) {
            addCriterion("image_seo_keyword <>", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordGreaterThan(String value) {
            addCriterion("image_seo_keyword >", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("image_seo_keyword >=", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordLessThan(String value) {
            addCriterion("image_seo_keyword <", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordLessThanOrEqualTo(String value) {
            addCriterion("image_seo_keyword <=", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordLike(String value) {
            addCriterion("image_seo_keyword like", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordNotLike(String value) {
            addCriterion("image_seo_keyword not like", value, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordIn(List<String> values) {
            addCriterion("image_seo_keyword in", values, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordNotIn(List<String> values) {
            addCriterion("image_seo_keyword not in", values, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordBetween(String value1, String value2) {
            addCriterion("image_seo_keyword between", value1, value2, "imageSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andImageSeoKeywordNotBetween(String value1, String value2) {
            addCriterion("image_seo_keyword not between", value1, value2, "imageSeoKeyword");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table image
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}