package com.hust.htd.persistence.model;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_url
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_url_thumb
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String imageUrlThumb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_seo_keyword
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String imageSeoKeyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_id
     *
     * @return the value of image.image_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_id
     *
     * @param imageId the value for image.image_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_url
     *
     * @return the value of image.image_url
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_url
     *
     * @param imageUrl the value for image.image_url
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_url_thumb
     *
     * @return the value of image.image_url_thumb
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getImageUrlThumb() {
        return imageUrlThumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_url_thumb
     *
     * @param imageUrlThumb the value for image.image_url_thumb
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setImageUrlThumb(String imageUrlThumb) {
        this.imageUrlThumb = imageUrlThumb == null ? null : imageUrlThumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_seo_keyword
     *
     * @return the value of image.image_seo_keyword
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getImageSeoKeyword() {
        return imageSeoKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_seo_keyword
     *
     * @param imageSeoKeyword the value for image.image_seo_keyword
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setImageSeoKeyword(String imageSeoKeyword) {
        this.imageSeoKeyword = imageSeoKeyword == null ? null : imageSeoKeyword.trim();
    }
}