package com.hust.htd.persistence.model;

public class Origin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column origin.origin_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long originId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column origin.origin_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String originName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column origin.origin_id
     *
     * @return the value of origin.origin_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getOriginId() {
        return originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column origin.origin_id
     *
     * @param originId the value for origin.origin_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOriginId(Long originId) {
        this.originId = originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column origin.origin_name
     *
     * @return the value of origin.origin_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column origin.origin_name
     *
     * @param originName the value for origin.origin_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOriginName(String originName) {
        this.originName = originName == null ? null : originName.trim();
    }
}