package com.hust.htd.persistence.model;

public class ProductImageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.image_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long imageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.product_id
     *
     * @return the value of product_image.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.product_id
     *
     * @param productId the value for product_image.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.image_id
     *
     * @return the value of product_image.image_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.image_id
     *
     * @param imageId the value for product_image.image_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }
}