package com.hust.htd.persistence.model;

public class ProductImage extends ProductImageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_image.primary_image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Boolean primaryImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_image.primary_image
     *
     * @return the value of product_image.primary_image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Boolean getPrimaryImage() {
        return primaryImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_image.primary_image
     *
     * @param primaryImage the value for product_image.primary_image
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setPrimaryImage(Boolean primaryImage) {
        this.primaryImage = primaryImage;
    }
}