package com.hust.htd.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNull() {
            addCriterion("product_price is null");
            return (Criteria) this;
        }

        public Criteria andProductPriceIsNotNull() {
            addCriterion("product_price is not null");
            return (Criteria) this;
        }

        public Criteria andProductPriceEqualTo(Float value) {
            addCriterion("product_price =", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotEqualTo(Float value) {
            addCriterion("product_price <>", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThan(Float value) {
            addCriterion("product_price >", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("product_price >=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThan(Float value) {
            addCriterion("product_price <", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceLessThanOrEqualTo(Float value) {
            addCriterion("product_price <=", value, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceIn(List<Float> values) {
            addCriterion("product_price in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotIn(List<Float> values) {
            addCriterion("product_price not in", values, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceBetween(Float value1, Float value2) {
            addCriterion("product_price between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductPriceNotBetween(Float value1, Float value2) {
            addCriterion("product_price not between", value1, value2, "productPrice");
            return (Criteria) this;
        }

        public Criteria andProductAvailableIsNull() {
            addCriterion("product_available is null");
            return (Criteria) this;
        }

        public Criteria andProductAvailableIsNotNull() {
            addCriterion("product_available is not null");
            return (Criteria) this;
        }

        public Criteria andProductAvailableEqualTo(Boolean value) {
            addCriterion("product_available =", value, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableNotEqualTo(Boolean value) {
            addCriterion("product_available <>", value, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableGreaterThan(Boolean value) {
            addCriterion("product_available >", value, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("product_available >=", value, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableLessThan(Boolean value) {
            addCriterion("product_available <", value, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableLessThanOrEqualTo(Boolean value) {
            addCriterion("product_available <=", value, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableIn(List<Boolean> values) {
            addCriterion("product_available in", values, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableNotIn(List<Boolean> values) {
            addCriterion("product_available not in", values, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableBetween(Boolean value1, Boolean value2) {
            addCriterion("product_available between", value1, value2, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductAvailableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("product_available not between", value1, value2, "productAvailable");
            return (Criteria) this;
        }

        public Criteria andProductShortDescIsNull() {
            addCriterion("product_short_desc is null");
            return (Criteria) this;
        }

        public Criteria andProductShortDescIsNotNull() {
            addCriterion("product_short_desc is not null");
            return (Criteria) this;
        }

        public Criteria andProductShortDescEqualTo(String value) {
            addCriterion("product_short_desc =", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescNotEqualTo(String value) {
            addCriterion("product_short_desc <>", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescGreaterThan(String value) {
            addCriterion("product_short_desc >", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescGreaterThanOrEqualTo(String value) {
            addCriterion("product_short_desc >=", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescLessThan(String value) {
            addCriterion("product_short_desc <", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescLessThanOrEqualTo(String value) {
            addCriterion("product_short_desc <=", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescLike(String value) {
            addCriterion("product_short_desc like", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescNotLike(String value) {
            addCriterion("product_short_desc not like", value, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescIn(List<String> values) {
            addCriterion("product_short_desc in", values, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescNotIn(List<String> values) {
            addCriterion("product_short_desc not in", values, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescBetween(String value1, String value2) {
            addCriterion("product_short_desc between", value1, value2, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductShortDescNotBetween(String value1, String value2) {
            addCriterion("product_short_desc not between", value1, value2, "productShortDesc");
            return (Criteria) this;
        }

        public Criteria andProductSizesIsNull() {
            addCriterion("product_sizes is null");
            return (Criteria) this;
        }

        public Criteria andProductSizesIsNotNull() {
            addCriterion("product_sizes is not null");
            return (Criteria) this;
        }

        public Criteria andProductSizesEqualTo(String value) {
            addCriterion("product_sizes =", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotEqualTo(String value) {
            addCriterion("product_sizes <>", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesGreaterThan(String value) {
            addCriterion("product_sizes >", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesGreaterThanOrEqualTo(String value) {
            addCriterion("product_sizes >=", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesLessThan(String value) {
            addCriterion("product_sizes <", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesLessThanOrEqualTo(String value) {
            addCriterion("product_sizes <=", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesLike(String value) {
            addCriterion("product_sizes like", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotLike(String value) {
            addCriterion("product_sizes not like", value, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesIn(List<String> values) {
            addCriterion("product_sizes in", values, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotIn(List<String> values) {
            addCriterion("product_sizes not in", values, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesBetween(String value1, String value2) {
            addCriterion("product_sizes between", value1, value2, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductSizesNotBetween(String value1, String value2) {
            addCriterion("product_sizes not between", value1, value2, "productSizes");
            return (Criteria) this;
        }

        public Criteria andProductColorsIsNull() {
            addCriterion("product_colors is null");
            return (Criteria) this;
        }

        public Criteria andProductColorsIsNotNull() {
            addCriterion("product_colors is not null");
            return (Criteria) this;
        }

        public Criteria andProductColorsEqualTo(String value) {
            addCriterion("product_colors =", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotEqualTo(String value) {
            addCriterion("product_colors <>", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsGreaterThan(String value) {
            addCriterion("product_colors >", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsGreaterThanOrEqualTo(String value) {
            addCriterion("product_colors >=", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsLessThan(String value) {
            addCriterion("product_colors <", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsLessThanOrEqualTo(String value) {
            addCriterion("product_colors <=", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsLike(String value) {
            addCriterion("product_colors like", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotLike(String value) {
            addCriterion("product_colors not like", value, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsIn(List<String> values) {
            addCriterion("product_colors in", values, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotIn(List<String> values) {
            addCriterion("product_colors not in", values, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsBetween(String value1, String value2) {
            addCriterion("product_colors between", value1, value2, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductColorsNotBetween(String value1, String value2) {
            addCriterion("product_colors not between", value1, value2, "productColors");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordIsNull() {
            addCriterion("product_seo_keyword is null");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordIsNotNull() {
            addCriterion("product_seo_keyword is not null");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordEqualTo(String value) {
            addCriterion("product_seo_keyword =", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordNotEqualTo(String value) {
            addCriterion("product_seo_keyword <>", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordGreaterThan(String value) {
            addCriterion("product_seo_keyword >", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("product_seo_keyword >=", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordLessThan(String value) {
            addCriterion("product_seo_keyword <", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordLessThanOrEqualTo(String value) {
            addCriterion("product_seo_keyword <=", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordLike(String value) {
            addCriterion("product_seo_keyword like", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordNotLike(String value) {
            addCriterion("product_seo_keyword not like", value, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordIn(List<String> values) {
            addCriterion("product_seo_keyword in", values, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordNotIn(List<String> values) {
            addCriterion("product_seo_keyword not in", values, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordBetween(String value1, String value2) {
            addCriterion("product_seo_keyword between", value1, value2, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andProductSeoKeywordNotBetween(String value1, String value2) {
            addCriterion("product_seo_keyword not between", value1, value2, "productSeoKeyword");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Long value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Long value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Long value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Long value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Long value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Long value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Long> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Long> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Long value1, Long value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Long value1, Long value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("brand_name is null");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("brand_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("brand_name =", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("brand_name <>", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("brand_name >", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("brand_name >=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("brand_name <", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("brand_name <=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("brand_name like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("brand_name not like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIn(List<String> values) {
            addCriterion("brand_name in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotIn(List<String> values) {
            addCriterion("brand_name not in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("brand_name between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("brand_name not between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameIsNull() {
            addCriterion("user_display_name is null");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameIsNotNull() {
            addCriterion("user_display_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameEqualTo(String value) {
            addCriterion("user_display_name =", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotEqualTo(String value) {
            addCriterion("user_display_name <>", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameGreaterThan(String value) {
            addCriterion("user_display_name >", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_display_name >=", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameLessThan(String value) {
            addCriterion("user_display_name <", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("user_display_name <=", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameLike(String value) {
            addCriterion("user_display_name like", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotLike(String value) {
            addCriterion("user_display_name not like", value, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameIn(List<String> values) {
            addCriterion("user_display_name in", values, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotIn(List<String> values) {
            addCriterion("user_display_name not in", values, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameBetween(String value1, String value2) {
            addCriterion("user_display_name between", value1, value2, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andUserDisplayNameNotBetween(String value1, String value2) {
            addCriterion("user_display_name not between", value1, value2, "userDisplayName");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlIsNull() {
            addCriterion("product_image_url is null");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlIsNotNull() {
            addCriterion("product_image_url is not null");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlEqualTo(String value) {
            addCriterion("product_image_url =", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlNotEqualTo(String value) {
            addCriterion("product_image_url <>", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlGreaterThan(String value) {
            addCriterion("product_image_url >", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("product_image_url >=", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlLessThan(String value) {
            addCriterion("product_image_url <", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlLessThanOrEqualTo(String value) {
            addCriterion("product_image_url <=", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlLike(String value) {
            addCriterion("product_image_url like", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlNotLike(String value) {
            addCriterion("product_image_url not like", value, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlIn(List<String> values) {
            addCriterion("product_image_url in", values, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlNotIn(List<String> values) {
            addCriterion("product_image_url not in", values, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlBetween(String value1, String value2) {
            addCriterion("product_image_url between", value1, value2, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductImageUrlNotBetween(String value1, String value2) {
            addCriterion("product_image_url not between", value1, value2, "productImageUrl");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedIsNull() {
            addCriterion("product_discounted is null");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedIsNotNull() {
            addCriterion("product_discounted is not null");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedEqualTo(Float value) {
            addCriterion("product_discounted =", value, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedNotEqualTo(Float value) {
            addCriterion("product_discounted <>", value, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedGreaterThan(Float value) {
            addCriterion("product_discounted >", value, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedGreaterThanOrEqualTo(Float value) {
            addCriterion("product_discounted >=", value, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedLessThan(Float value) {
            addCriterion("product_discounted <", value, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedLessThanOrEqualTo(Float value) {
            addCriterion("product_discounted <=", value, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedIn(List<Float> values) {
            addCriterion("product_discounted in", values, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedNotIn(List<Float> values) {
            addCriterion("product_discounted not in", values, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedBetween(Float value1, Float value2) {
            addCriterion("product_discounted between", value1, value2, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductDiscountedNotBetween(Float value1, Float value2) {
            addCriterion("product_discounted not between", value1, value2, "productDiscounted");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeIsNull() {
            addCriterion("product_expired_datetime is null");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeIsNotNull() {
            addCriterion("product_expired_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeEqualTo(Date value) {
            addCriterion("product_expired_datetime =", value, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeNotEqualTo(Date value) {
            addCriterion("product_expired_datetime <>", value, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeGreaterThan(Date value) {
            addCriterion("product_expired_datetime >", value, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("product_expired_datetime >=", value, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeLessThan(Date value) {
            addCriterion("product_expired_datetime <", value, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("product_expired_datetime <=", value, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeIn(List<Date> values) {
            addCriterion("product_expired_datetime in", values, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeNotIn(List<Date> values) {
            addCriterion("product_expired_datetime not in", values, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeBetween(Date value1, Date value2) {
            addCriterion("product_expired_datetime between", value1, value2, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductExpiredDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("product_expired_datetime not between", value1, value2, "productExpiredDatetime");
            return (Criteria) this;
        }

        public Criteria andProductViewedIsNull() {
            addCriterion("product_viewed is null");
            return (Criteria) this;
        }

        public Criteria andProductViewedIsNotNull() {
            addCriterion("product_viewed is not null");
            return (Criteria) this;
        }

        public Criteria andProductViewedEqualTo(Integer value) {
            addCriterion("product_viewed =", value, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedNotEqualTo(Integer value) {
            addCriterion("product_viewed <>", value, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedGreaterThan(Integer value) {
            addCriterion("product_viewed >", value, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_viewed >=", value, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedLessThan(Integer value) {
            addCriterion("product_viewed <", value, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedLessThanOrEqualTo(Integer value) {
            addCriterion("product_viewed <=", value, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedIn(List<Integer> values) {
            addCriterion("product_viewed in", values, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedNotIn(List<Integer> values) {
            addCriterion("product_viewed not in", values, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedBetween(Integer value1, Integer value2) {
            addCriterion("product_viewed between", value1, value2, "productViewed");
            return (Criteria) this;
        }

        public Criteria andProductViewedNotBetween(Integer value1, Integer value2) {
            addCriterion("product_viewed not between", value1, value2, "productViewed");
            return (Criteria) this;
        }

        public Criteria andOriginIdIsNull() {
            addCriterion("origin_id is null");
            return (Criteria) this;
        }

        public Criteria andOriginIdIsNotNull() {
            addCriterion("origin_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriginIdEqualTo(Long value) {
            addCriterion("origin_id =", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdNotEqualTo(Long value) {
            addCriterion("origin_id <>", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdGreaterThan(Long value) {
            addCriterion("origin_id >", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdGreaterThanOrEqualTo(Long value) {
            addCriterion("origin_id >=", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdLessThan(Long value) {
            addCriterion("origin_id <", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdLessThanOrEqualTo(Long value) {
            addCriterion("origin_id <=", value, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdIn(List<Long> values) {
            addCriterion("origin_id in", values, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdNotIn(List<Long> values) {
            addCriterion("origin_id not in", values, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdBetween(Long value1, Long value2) {
            addCriterion("origin_id between", value1, value2, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginIdNotBetween(Long value1, Long value2) {
            addCriterion("origin_id not between", value1, value2, "originId");
            return (Criteria) this;
        }

        public Criteria andOriginNameIsNull() {
            addCriterion("origin_name is null");
            return (Criteria) this;
        }

        public Criteria andOriginNameIsNotNull() {
            addCriterion("origin_name is not null");
            return (Criteria) this;
        }

        public Criteria andOriginNameEqualTo(String value) {
            addCriterion("origin_name =", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameNotEqualTo(String value) {
            addCriterion("origin_name <>", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameGreaterThan(String value) {
            addCriterion("origin_name >", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameGreaterThanOrEqualTo(String value) {
            addCriterion("origin_name >=", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameLessThan(String value) {
            addCriterion("origin_name <", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameLessThanOrEqualTo(String value) {
            addCriterion("origin_name <=", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameLike(String value) {
            addCriterion("origin_name like", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameNotLike(String value) {
            addCriterion("origin_name not like", value, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameIn(List<String> values) {
            addCriterion("origin_name in", values, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameNotIn(List<String> values) {
            addCriterion("origin_name not in", values, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameBetween(String value1, String value2) {
            addCriterion("origin_name between", value1, value2, "originName");
            return (Criteria) this;
        }

        public Criteria andOriginNameNotBetween(String value1, String value2) {
            addCriterion("origin_name not between", value1, value2, "originName");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeIsNull() {
            addCriterion("product_created_datetime is null");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeIsNotNull() {
            addCriterion("product_created_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeEqualTo(Date value) {
            addCriterion("product_created_datetime =", value, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeNotEqualTo(Date value) {
            addCriterion("product_created_datetime <>", value, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeGreaterThan(Date value) {
            addCriterion("product_created_datetime >", value, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("product_created_datetime >=", value, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeLessThan(Date value) {
            addCriterion("product_created_datetime <", value, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("product_created_datetime <=", value, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeIn(List<Date> values) {
            addCriterion("product_created_datetime in", values, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeNotIn(List<Date> values) {
            addCriterion("product_created_datetime not in", values, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeBetween(Date value1, Date value2) {
            addCriterion("product_created_datetime between", value1, value2, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductCreatedDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("product_created_datetime not between", value1, value2, "productCreatedDatetime");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerIsNull() {
            addCriterion("product_best_seller is null");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerIsNotNull() {
            addCriterion("product_best_seller is not null");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerEqualTo(Boolean value) {
            addCriterion("product_best_seller =", value, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerNotEqualTo(Boolean value) {
            addCriterion("product_best_seller <>", value, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerGreaterThan(Boolean value) {
            addCriterion("product_best_seller >", value, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerGreaterThanOrEqualTo(Boolean value) {
            addCriterion("product_best_seller >=", value, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerLessThan(Boolean value) {
            addCriterion("product_best_seller <", value, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerLessThanOrEqualTo(Boolean value) {
            addCriterion("product_best_seller <=", value, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerIn(List<Boolean> values) {
            addCriterion("product_best_seller in", values, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerNotIn(List<Boolean> values) {
            addCriterion("product_best_seller not in", values, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerBetween(Boolean value1, Boolean value2) {
            addCriterion("product_best_seller between", value1, value2, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andProductBestSellerNotBetween(Boolean value1, Boolean value2) {
            addCriterion("product_best_seller not between", value1, value2, "productBestSeller");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdIsNull() {
            addCriterion("subcategory_id is null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdIsNotNull() {
            addCriterion("subcategory_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdEqualTo(Long value) {
            addCriterion("subcategory_id =", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdNotEqualTo(Long value) {
            addCriterion("subcategory_id <>", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdGreaterThan(Long value) {
            addCriterion("subcategory_id >", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subcategory_id >=", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdLessThan(Long value) {
            addCriterion("subcategory_id <", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("subcategory_id <=", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdIn(List<Long> values) {
            addCriterion("subcategory_id in", values, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdNotIn(List<Long> values) {
            addCriterion("subcategory_id not in", values, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdBetween(Long value1, Long value2) {
            addCriterion("subcategory_id between", value1, value2, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("subcategory_id not between", value1, value2, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameIsNull() {
            addCriterion("subcategory_name is null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameIsNotNull() {
            addCriterion("subcategory_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameEqualTo(String value) {
            addCriterion("subcategory_name =", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotEqualTo(String value) {
            addCriterion("subcategory_name <>", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameGreaterThan(String value) {
            addCriterion("subcategory_name >", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("subcategory_name >=", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameLessThan(String value) {
            addCriterion("subcategory_name <", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameLessThanOrEqualTo(String value) {
            addCriterion("subcategory_name <=", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameLike(String value) {
            addCriterion("subcategory_name like", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotLike(String value) {
            addCriterion("subcategory_name not like", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameIn(List<String> values) {
            addCriterion("subcategory_name in", values, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotIn(List<String> values) {
            addCriterion("subcategory_name not in", values, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameBetween(String value1, String value2) {
            addCriterion("subcategory_name between", value1, value2, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotBetween(String value1, String value2) {
            addCriterion("subcategory_name not between", value1, value2, "subcategoryName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}