package com.hust.htd.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class RateSnippetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public RateSnippetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andRateAvgIsNull() {
            addCriterion("rate_avg is null");
            return (Criteria) this;
        }

        public Criteria andRateAvgIsNotNull() {
            addCriterion("rate_avg is not null");
            return (Criteria) this;
        }

        public Criteria andRateAvgEqualTo(Float value) {
            addCriterion("rate_avg =", value, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgNotEqualTo(Float value) {
            addCriterion("rate_avg <>", value, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgGreaterThan(Float value) {
            addCriterion("rate_avg >", value, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgGreaterThanOrEqualTo(Float value) {
            addCriterion("rate_avg >=", value, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgLessThan(Float value) {
            addCriterion("rate_avg <", value, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgLessThanOrEqualTo(Float value) {
            addCriterion("rate_avg <=", value, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgIn(List<Float> values) {
            addCriterion("rate_avg in", values, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgNotIn(List<Float> values) {
            addCriterion("rate_avg not in", values, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgBetween(Float value1, Float value2) {
            addCriterion("rate_avg between", value1, value2, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateAvgNotBetween(Float value1, Float value2) {
            addCriterion("rate_avg not between", value1, value2, "rateAvg");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserIsNull() {
            addCriterion("rate_total_user is null");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserIsNotNull() {
            addCriterion("rate_total_user is not null");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserEqualTo(Integer value) {
            addCriterion("rate_total_user =", value, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserNotEqualTo(Integer value) {
            addCriterion("rate_total_user <>", value, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserGreaterThan(Integer value) {
            addCriterion("rate_total_user >", value, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("rate_total_user >=", value, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserLessThan(Integer value) {
            addCriterion("rate_total_user <", value, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserLessThanOrEqualTo(Integer value) {
            addCriterion("rate_total_user <=", value, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserIn(List<Integer> values) {
            addCriterion("rate_total_user in", values, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserNotIn(List<Integer> values) {
            addCriterion("rate_total_user not in", values, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserBetween(Integer value1, Integer value2) {
            addCriterion("rate_total_user between", value1, value2, "rateTotalUser");
            return (Criteria) this;
        }

        public Criteria andRateTotalUserNotBetween(Integer value1, Integer value2) {
            addCriterion("rate_total_user not between", value1, value2, "rateTotalUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rate_snippet
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}