package com.hust.htd.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public RateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRateIdIsNull() {
            addCriterion("rate_id is null");
            return (Criteria) this;
        }

        public Criteria andRateIdIsNotNull() {
            addCriterion("rate_id is not null");
            return (Criteria) this;
        }

        public Criteria andRateIdEqualTo(Long value) {
            addCriterion("rate_id =", value, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdNotEqualTo(Long value) {
            addCriterion("rate_id <>", value, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdGreaterThan(Long value) {
            addCriterion("rate_id >", value, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdGreaterThanOrEqualTo(Long value) {
            addCriterion("rate_id >=", value, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdLessThan(Long value) {
            addCriterion("rate_id <", value, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdLessThanOrEqualTo(Long value) {
            addCriterion("rate_id <=", value, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdIn(List<Long> values) {
            addCriterion("rate_id in", values, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdNotIn(List<Long> values) {
            addCriterion("rate_id not in", values, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdBetween(Long value1, Long value2) {
            addCriterion("rate_id between", value1, value2, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateIdNotBetween(Long value1, Long value2) {
            addCriterion("rate_id not between", value1, value2, "rateId");
            return (Criteria) this;
        }

        public Criteria andRateValueIsNull() {
            addCriterion("rate_value is null");
            return (Criteria) this;
        }

        public Criteria andRateValueIsNotNull() {
            addCriterion("rate_value is not null");
            return (Criteria) this;
        }

        public Criteria andRateValueEqualTo(Float value) {
            addCriterion("rate_value =", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueNotEqualTo(Float value) {
            addCriterion("rate_value <>", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueGreaterThan(Float value) {
            addCriterion("rate_value >", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueGreaterThanOrEqualTo(Float value) {
            addCriterion("rate_value >=", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueLessThan(Float value) {
            addCriterion("rate_value <", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueLessThanOrEqualTo(Float value) {
            addCriterion("rate_value <=", value, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueIn(List<Float> values) {
            addCriterion("rate_value in", values, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueNotIn(List<Float> values) {
            addCriterion("rate_value not in", values, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueBetween(Float value1, Float value2) {
            addCriterion("rate_value between", value1, value2, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateValueNotBetween(Float value1, Float value2) {
            addCriterion("rate_value not between", value1, value2, "rateValue");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeIsNull() {
            addCriterion("rate_datetime is null");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeIsNotNull() {
            addCriterion("rate_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeEqualTo(Date value) {
            addCriterion("rate_datetime =", value, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeNotEqualTo(Date value) {
            addCriterion("rate_datetime <>", value, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeGreaterThan(Date value) {
            addCriterion("rate_datetime >", value, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("rate_datetime >=", value, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeLessThan(Date value) {
            addCriterion("rate_datetime <", value, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("rate_datetime <=", value, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeIn(List<Date> values) {
            addCriterion("rate_datetime in", values, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeNotIn(List<Date> values) {
            addCriterion("rate_datetime not in", values, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeBetween(Date value1, Date value2) {
            addCriterion("rate_datetime between", value1, value2, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andRateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("rate_datetime not between", value1, value2, "rateDatetime");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdIsNull() {
            addCriterion("anonymous_id is null");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdIsNotNull() {
            addCriterion("anonymous_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdEqualTo(Long value) {
            addCriterion("anonymous_id =", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdNotEqualTo(Long value) {
            addCriterion("anonymous_id <>", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdGreaterThan(Long value) {
            addCriterion("anonymous_id >", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdGreaterThanOrEqualTo(Long value) {
            addCriterion("anonymous_id >=", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdLessThan(Long value) {
            addCriterion("anonymous_id <", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdLessThanOrEqualTo(Long value) {
            addCriterion("anonymous_id <=", value, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdIn(List<Long> values) {
            addCriterion("anonymous_id in", values, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdNotIn(List<Long> values) {
            addCriterion("anonymous_id not in", values, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdBetween(Long value1, Long value2) {
            addCriterion("anonymous_id between", value1, value2, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andAnonymousIdNotBetween(Long value1, Long value2) {
            addCriterion("anonymous_id not between", value1, value2, "anonymousId");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rate
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}