package com.hust.htd.persistence.model;

public class RateSnippet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_snippet.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_snippet.rate_avg
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Float rateAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate_snippet.rate_total_user
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Integer rateTotalUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_snippet.product_id
     *
     * @return the value of rate_snippet.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_snippet.product_id
     *
     * @param productId the value for rate_snippet.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_snippet.rate_avg
     *
     * @return the value of rate_snippet.rate_avg
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Float getRateAvg() {
        return rateAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_snippet.rate_avg
     *
     * @param rateAvg the value for rate_snippet.rate_avg
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setRateAvg(Float rateAvg) {
        this.rateAvg = rateAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate_snippet.rate_total_user
     *
     * @return the value of rate_snippet.rate_total_user
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Integer getRateTotalUser() {
        return rateTotalUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate_snippet.rate_total_user
     *
     * @param rateTotalUser the value for rate_snippet.rate_total_user
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setRateTotalUser(Integer rateTotalUser) {
        this.rateTotalUser = rateTotalUser;
    }
}