package com.hust.htd.persistence.model;

import java.util.Date;

public class Rate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate.rate_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long rateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate.rate_value
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Float rateValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate.rate_datetime
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Date rateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate.anonymous_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long anonymousId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rate.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate.rate_id
     *
     * @return the value of rate.rate_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getRateId() {
        return rateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate.rate_id
     *
     * @param rateId the value for rate.rate_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setRateId(Long rateId) {
        this.rateId = rateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate.rate_value
     *
     * @return the value of rate.rate_value
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Float getRateValue() {
        return rateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate.rate_value
     *
     * @param rateValue the value for rate.rate_value
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setRateValue(Float rateValue) {
        this.rateValue = rateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate.rate_datetime
     *
     * @return the value of rate.rate_datetime
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Date getRateDatetime() {
        return rateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate.rate_datetime
     *
     * @param rateDatetime the value for rate.rate_datetime
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setRateDatetime(Date rateDatetime) {
        this.rateDatetime = rateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate.anonymous_id
     *
     * @return the value of rate.anonymous_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getAnonymousId() {
        return anonymousId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate.anonymous_id
     *
     * @param anonymousId the value for rate.anonymous_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setAnonymousId(Long anonymousId) {
        this.anonymousId = anonymousId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rate.product_id
     *
     * @return the value of rate.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rate.product_id
     *
     * @param productId the value for rate.product_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }
}