package com.hust.htd.persistence.model;

public class SubCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subcategory.subcategory_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long subcategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subcategory.subcategory_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String subcategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subcategory.subcategory_info
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private String subcategoryInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subcategory.category_parent_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    private Long categoryParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subcategory.subcategory_id
     *
     * @return the value of subcategory.subcategory_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getSubcategoryId() {
        return subcategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subcategory.subcategory_id
     *
     * @param subcategoryId the value for subcategory.subcategory_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setSubcategoryId(Long subcategoryId) {
        this.subcategoryId = subcategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subcategory.subcategory_name
     *
     * @return the value of subcategory.subcategory_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getSubcategoryName() {
        return subcategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subcategory.subcategory_name
     *
     * @param subcategoryName the value for subcategory.subcategory_name
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setSubcategoryName(String subcategoryName) {
        this.subcategoryName = subcategoryName == null ? null : subcategoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subcategory.subcategory_info
     *
     * @return the value of subcategory.subcategory_info
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getSubcategoryInfo() {
        return subcategoryInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subcategory.subcategory_info
     *
     * @param subcategoryInfo the value for subcategory.subcategory_info
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setSubcategoryInfo(String subcategoryInfo) {
        this.subcategoryInfo = subcategoryInfo == null ? null : subcategoryInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subcategory.category_parent_id
     *
     * @return the value of subcategory.category_parent_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Long getCategoryParentId() {
        return categoryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subcategory.category_parent_id
     *
     * @param categoryParentId the value for subcategory.category_parent_id
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setCategoryParentId(Long categoryParentId) {
        this.categoryParentId = categoryParentId;
    }
}