package com.hust.htd.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class SubCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public SubCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubcategoryIdIsNull() {
            addCriterion("subcategory_id is null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdIsNotNull() {
            addCriterion("subcategory_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdEqualTo(Long value) {
            addCriterion("subcategory_id =", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdNotEqualTo(Long value) {
            addCriterion("subcategory_id <>", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdGreaterThan(Long value) {
            addCriterion("subcategory_id >", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subcategory_id >=", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdLessThan(Long value) {
            addCriterion("subcategory_id <", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("subcategory_id <=", value, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdIn(List<Long> values) {
            addCriterion("subcategory_id in", values, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdNotIn(List<Long> values) {
            addCriterion("subcategory_id not in", values, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdBetween(Long value1, Long value2) {
            addCriterion("subcategory_id between", value1, value2, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("subcategory_id not between", value1, value2, "subcategoryId");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameIsNull() {
            addCriterion("subcategory_name is null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameIsNotNull() {
            addCriterion("subcategory_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameEqualTo(String value) {
            addCriterion("subcategory_name =", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotEqualTo(String value) {
            addCriterion("subcategory_name <>", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameGreaterThan(String value) {
            addCriterion("subcategory_name >", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameGreaterThanOrEqualTo(String value) {
            addCriterion("subcategory_name >=", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameLessThan(String value) {
            addCriterion("subcategory_name <", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameLessThanOrEqualTo(String value) {
            addCriterion("subcategory_name <=", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameLike(String value) {
            addCriterion("subcategory_name like", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotLike(String value) {
            addCriterion("subcategory_name not like", value, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameIn(List<String> values) {
            addCriterion("subcategory_name in", values, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotIn(List<String> values) {
            addCriterion("subcategory_name not in", values, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameBetween(String value1, String value2) {
            addCriterion("subcategory_name between", value1, value2, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryNameNotBetween(String value1, String value2) {
            addCriterion("subcategory_name not between", value1, value2, "subcategoryName");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoIsNull() {
            addCriterion("subcategory_info is null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoIsNotNull() {
            addCriterion("subcategory_info is not null");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoEqualTo(String value) {
            addCriterion("subcategory_info =", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoNotEqualTo(String value) {
            addCriterion("subcategory_info <>", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoGreaterThan(String value) {
            addCriterion("subcategory_info >", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoGreaterThanOrEqualTo(String value) {
            addCriterion("subcategory_info >=", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoLessThan(String value) {
            addCriterion("subcategory_info <", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoLessThanOrEqualTo(String value) {
            addCriterion("subcategory_info <=", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoLike(String value) {
            addCriterion("subcategory_info like", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoNotLike(String value) {
            addCriterion("subcategory_info not like", value, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoIn(List<String> values) {
            addCriterion("subcategory_info in", values, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoNotIn(List<String> values) {
            addCriterion("subcategory_info not in", values, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoBetween(String value1, String value2) {
            addCriterion("subcategory_info between", value1, value2, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andSubcategoryInfoNotBetween(String value1, String value2) {
            addCriterion("subcategory_info not between", value1, value2, "subcategoryInfo");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdIsNull() {
            addCriterion("category_parent_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdIsNotNull() {
            addCriterion("category_parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdEqualTo(Long value) {
            addCriterion("category_parent_id =", value, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdNotEqualTo(Long value) {
            addCriterion("category_parent_id <>", value, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdGreaterThan(Long value) {
            addCriterion("category_parent_id >", value, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("category_parent_id >=", value, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdLessThan(Long value) {
            addCriterion("category_parent_id <", value, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdLessThanOrEqualTo(Long value) {
            addCriterion("category_parent_id <=", value, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdIn(List<Long> values) {
            addCriterion("category_parent_id in", values, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdNotIn(List<Long> values) {
            addCriterion("category_parent_id not in", values, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdBetween(Long value1, Long value2) {
            addCriterion("category_parent_id between", value1, value2, "categoryParentId");
            return (Criteria) this;
        }

        public Criteria andCategoryParentIdNotBetween(Long value1, Long value2) {
            addCriterion("category_parent_id not between", value1, value2, "categoryParentId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subcategory
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}