package com.hust.htd.persistence.mapper;

import com.hust.htd.persistence.model.Anonymous;
import com.hust.htd.persistence.model.AnonymousExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnonymousMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int countByExample(AnonymousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByExample(AnonymousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByPrimaryKey(Long anonymousId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insert(Anonymous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insertSelective(Anonymous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    List<Anonymous> selectByExample(AnonymousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    Anonymous selectByPrimaryKey(Long anonymousId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Anonymous record, @Param("example") AnonymousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExample(@Param("record") Anonymous record, @Param("example") AnonymousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKeySelective(Anonymous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anonymous
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKey(Anonymous record);
}