package com.hust.htd.persistence.mapper;

import com.hust.htd.persistence.model.Brand;
import com.hust.htd.persistence.model.BrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByPrimaryKey(Long brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    Brand selectByPrimaryKey(Long brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExample(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKey(Brand record);
}