package com.hust.htd.persistence.mapper;

import com.hust.htd.persistence.model.Origin;
import com.hust.htd.persistence.model.OriginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OriginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int countByExample(OriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByExample(OriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByPrimaryKey(Long originId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insert(Origin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insertSelective(Origin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    List<Origin> selectByExample(OriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    Origin selectByPrimaryKey(Long originId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Origin record, @Param("example") OriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExample(@Param("record") Origin record, @Param("example") OriginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKeySelective(Origin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table origin
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKey(Origin record);
}