package com.hust.htd.persistence.mapper;

import com.hust.htd.persistence.model.RateSnippet;
import com.hust.htd.persistence.model.RateSnippetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RateSnippetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int countByExample(RateSnippetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByExample(RateSnippetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insert(RateSnippet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insertSelective(RateSnippet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    List<RateSnippet> selectByExample(RateSnippetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    RateSnippet selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") RateSnippet record, @Param("example") RateSnippetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExample(@Param("record") RateSnippet record, @Param("example") RateSnippetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKeySelective(RateSnippet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate_snippet
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKey(RateSnippet record);
}