package com.hust.htd.persistence.mapper;

import com.hust.htd.persistence.model.Rate;
import com.hust.htd.persistence.model.RateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int countByExample(RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByExample(RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByPrimaryKey(Long rateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insert(Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insertSelective(Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    List<Rate> selectByExample(RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    Rate selectByPrimaryKey(Long rateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") Rate record, @Param("example") RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExample(@Param("record") Rate record, @Param("example") RateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKeySelective(Rate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rate
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKey(Rate record);
}