package com.hust.htd.persistence.mapper;

import com.hust.htd.persistence.model.SubCategory;
import com.hust.htd.persistence.model.SubCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int countByExample(SubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByExample(SubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int deleteByPrimaryKey(Long subcategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insert(SubCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int insertSelective(SubCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    List<SubCategory> selectByExample(SubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    SubCategory selectByPrimaryKey(Long subcategoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExampleSelective(@Param("record") SubCategory record, @Param("example") SubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByExample(@Param("record") SubCategory record, @Param("example") SubCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKeySelective(SubCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subcategory
     *
     * @mbggenerated Sun Oct 25 18:48:50 ICT 2015
     */
    int updateByPrimaryKey(SubCategory record);
}